baseURL = "https://brsrk94.github.io/0xPaper/"
languageCode = "en-us"
title = "0xPaper"
theme = "catppuccin-minimal"

[params]
  siteDescription = "by Aditya Tomar"
  author = "Aditya Tomar"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
  style = "dracula"
    tabWidth = 2
